name: proxycheck
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - requests>=2.28
    - ipwhois>=1.1.0
    - python-dotenv>=1.0
    - PyYAML>=6.0
    - tqdm>=4.65
    - pytest>=7.0
